################ Lunchfun & Dictionary
http://localhost/api/lunchfun/pals
###############

POST http://localhost/api/lunchfun/pal HTTP/1.1
content-type: application/json

{
    "name": "homie"
}

###################

DELETE http://localhost/api/lunchfun/pal?name=homie

####
http://localhost/api/lunchfun/records

####
POST http://localhost/api/lunchfun/record HTTP/1.1
content-type: application/json

{
    "payer": "Eddie",
    "attendees": ["Eddie","Samuel"]
}

####
DELETE http://localhost/api/lunchfun/record?_id=5c263eabe5ecb60e50c38602

###
http://localhost/api/lunchfun/stats/attendance

### 
http://localhost/api/dict/

