################ Get product
http://localhost:8080/api/gifts/products/product?id=2

############### Add product

POST http://localhost:8080/api/gifts/products/product HTTP/1.1
content-type: application/json

{
    "name": "Bag3",
    "category": "/Bags",
    "price": 5.9,
    "packaging": "NA.",
    "material": "Nilon",
    "size": "35x28x15 cm",
    "note": "no note."
}

############################# Edit product

PUT http://localhost:8080/api/gifts/products/product HTTP/1.1
content-type: application/json

{
    "id": 2,
    "img": ["electronics1.jpg"],
    "name": "IT",
    "category": "/IT",
    "price": 5.50,
    "packaging": "metal",
    "material": "Copper",
    "size": "100x50x50 cm",
    "note": "no note.",
    "retailer": "fg"
}

################### Delete product

DELETE http://localhost:8080/api/gifts/products/product?id=1

################### Get Inventory

http://localhost/api/gifts/products/inventory

################### Edit Inventory

PUT http://localhost/api/gifts/products/inventory HTTP/1.1
content-type: application/json

{
    "product": 
    {
        "_id": "5c28b72583495120102b82a4"
    },
    "qty": 40
}

################### Get catalog
http://localhost/api/gifts/products/samples


################### Get products by category
http://localhost:8080/api/gifts/products?category=/Bags

################### Get categories
http://localhost:8080/api/gifts/products/categories

############### Add category

POST http://localhost:8080/api/gifts/products/category HTTP/1.1
content-type: application/json

{
    "name": "Pencil",
    "parent": "/stationary"
}
############### Edit category

PUT http://localhost:8080/api/gifts/products/category HTTP/1.1
content-type: application/json

{
    "org":{
        "name": "Pen-New",
        "category":"undefined/Pen-New"
    },
    "newName": "Pen"
}
############### delete category

DELETE  http://localhost:8080/api/gifts/products/category?category=[object Object]/Pencil
