################  Dictionary
http://localhost/api/gifts/users/logout
###############

###############
https://45.76.197.18:444

###############

POST http://localhost/api/gifts/users/login HTTP/1.1
content-type: application/json

{
    "uid": "a",
    "pwd": "a",
    "email": "t@email.com"
}
//5c285b738689792ca4ed91f6

###################

POST http://localhost/api/gifts/users/register HTTP/1.1
content-type: application/json

{
    "uid": "a",
    "pwd": "a",
    "email": "a@email.com"
}

###################
DELETE http://localhost/api/gifts/users/deleteuser
