import {
  faLeaf,
  faSignInAlt,
  faSignOutAlt,
  faUser,
  faKey,
  faAnchor,
  faFileWord,
  faPaperPlane,
  faChevronDown,
  faShoppingCart,
  faChevronLeft,
  faChevronRight,
  faTrash,
  faHeart,
  faSearch,
  faPlay,
  faCheck,
  faChevronCircleUp,
  faPhone,
  faEnvelope,
  faMapMarker,
  faAlignJustify,
  faInfo,
  faIdCardAlt,
  faEnvelopeOpen,
  faMobileAlt,
  faDesktop
} from '@fortawesome/free-solid-svg-icons';
// import {
//   faWhatsapp,
//   faFacebook,
//   faTwitter,
//   faLinkedin,
//   faWeixin
// } from '@fortawesome/free-brands-svg-icons';

export const fontawesomeIcons = [
  faAlignJustify,
  faAnchor,
  faCheck,
  faChevronCircleUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faDesktop,
  faEnvelope,
  faEnvelopeOpen,
  faFileWord,
  faHeart,
  faIdCardAlt,
  faLeaf,
  faMapMarker,
  faMobileAlt,
  faKey,
  faPaperPlane,
  faPhone,
  faPlay,
  faSearch,
  faShoppingCart,
  faSignInAlt,
  faSignOutAlt,
  faTrash,
  faUser,
  faInfo
  // faFacebook,
  // faTwitter,
  // faWhatsapp,
  // faLinkedin,
  // faWeixin
];
